[package]
name = "at-comments"
version = "0.4.1"
edition = "2021"
license = "MIT"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
jetstream-oxide = "0.1.2"
atrium-api = "0.25.6"
log = "0.4.25"
serde = "1.0.217"
chrono = "0.4.41"
[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_postgres"]
